# Theme metadata
name = "paso_theme"

# Is theme light or dark?
light = true

# Primary
primary = "#A9D640"

# Menu
menu_primary = "#A9D640"
menu_text = "White"
menu_text_active = "OrangeRed"
menu_title = "#2b2b2b"

# Home sections
home_section_odd = "rgb(255, 255, 255)"
home_section_even = "rgb(247, 247, 247)"
